[package]
name = "swarm-lib"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
cortex-m.workspace = true
defmt.workspace = true
defmt-rtt.workspace = true
cyw43.workspace = true
cyw43-pio.workspace = true
embassy-executor.workspace = true
embassy-net.workspace = true
embassy-rp.workspace = true
embassy-time.workspace = true
embassy-usb-logger.workspace = true
log.workspace = true
static_cell.workspace = true
embassy-futures.workspace = true
fixed.workspace = true
pio.workspace = true
pio-proc.workspace = true
embedded-hal-async.workspace = true
embedded-graphics.workspace = true
