site_name: aggregator
site_description: Aggregator for multiple Raspberry Pi Picos for a dumb smart home

theme:
  name: material
  palette:
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.sections
    - search.suggest

plugins:
  - search
  - gen-files:
      scripts:
        - docs/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true
            members_order: source
            docstring_style: google
            # Uncomment to include private (_prefixed) members in the docs:
            # filters: ["!^__"]

nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - API Reference: api/
